[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/submission-created.js"]
  [functions.submission-created]
    form = "admissions"
    email_template = "/static/email.html"
