[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  [functions.submission-created]
    [functions.submission-created.admissions]
      email_template = "/static/email.html"
